### ISSUE TITLE
[FR] dynamically set IDP cert and assert endpoint

### ISSUE THREAD

**Issue by rayfoss** [winteragency/feathers-saml#15]
I'm planning to make a PR that would allow dynamically setting IDP cert and assert path. Ideally allowing runtime configuration of the IDP.

I welcome ideas.

- Redirect URL already supports domain relative paths.
- IDP cert seems a bit unnecessary in HTTPS contexts, not sure if the is a SAML limitation

**Comment by rlunden** [comment]
Merged your PR. Created a new version with it along with update to saml2-js.
